/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs:[
    {
      type: 'category',
      label: 'What is Nacos',
      collapsible: false,
      items: ['what-is-nacos', 'concepts', 'architecture'],
    },
    {
      type: 'category',
      label: 'Quick Start',
      collapsible: false,
      items: ['quickstart/quick-start', 'quickstart/quick-start-docker', 'quickstart/quick-start-kubernetes'],
    },
    {
      type: 'category',
      label: 'Upgrading',
      collapsible: false,
      items: ['upgrading/2.0.0-compatibility', 'upgrading/2.0.0-upgrading'],
    },
    {
      type: 'category',
      label: 'Plugin',
      collapsible: false,
      items: ['plugin/auth-plugin', 'plugin/config-encryption-plugin','plugin/datasource-plugin','plugin/trace-plugin','plugin/custom-environment-plugin','plugin/config-change-plugin','plugin/control-plugin'],
    },
    {
      type: 'category',
      label: 'User Guide',
      collapsible: false,
      items: ['guide/user/sdk', 'guide/user/other-language', 'guide/user/open-api','guide/user/auth','guide/user/faq','guide/user/parameters-check','guide/user/failover'],
    },
    {
      type: 'category',
      label: 'Admin Guide',
      collapsible: false,
      items: ['guide/admin/deployment',
        'guide/admin/cluster-mode-quick-start',
        'guide/admin/system-configurations',
        'guide/admin/management-api',
        'guide/admin/console-guide',
        'guide/admin/monitor-guide',
        'guide/admin/nacos2-config-benchmark',
        'guide/admin/nacos2-naming-benchmark',
        'ecology/use-nacos-sync',
      ],
    },
    {
      type: 'category',
      label: 'Ecology',
      collapsible: false,
      items: ['ecology/use-nacos-with-dubbo',
        'ecology/use-nacos-with-spring',
        'ecology/use-nacos-with-spring-boot',
        'ecology/use-nacos-with-spring-cloud',
        'ecology/use-nacos-sync',
        'ecology/use-nacos-with-coredns',
      ],
    },
    {
      type: 'category',
      label: 'Contributor Guide',
      collapsible: false,
      items: ['contribution/contributing',
        'contribution/contributing-flow',
        'contribution/pull-request',
        'contribution/how-to-reporting-bugs',
      ],
    },
    {
      type: 'category',
      label: 'Community',
      collapsible: false,
      items: ['community/community', 'community/nacos-dev',],
    },
  ]

  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
